### ISSUE TITLE
get_jsvalue will parse large utf8 value into json by default

### ISSUE THREAD

**Issue by sundy-li** [risingwavelabs/arrow-udf#16]
I think this code is not arrow-compatible, is it used just for `risingwave`? Maybe it's better to use extension type.
```
       // json type
        DataType::LargeUtf8 => {
            let array = array.as_any().downcast_ref::<LargeStringArray>().unwrap();
            ctx.json_parse(array.value(i))
        }
        // decimal type
        DataType::LargeBinary => {
            let array = array.as_any().downcast_ref::<LargeBinaryArray>().unwrap();
            let string = std::str::from_utf8(array.value(i))?;
            bigdecimal.call((string,))
        }

```

https://github.com/risingwavelabs/arrow-udf/compare/main...datafuse-extras:arrow-udf:large-utf8

**Comment by wangrunji0408** [comment]
Yes, this is a private protocol for RisingWave to exchange values in json and decimal type. Apologize for it as it is not well-documented. I am also thinking about using extension type. Will fix it in the next version.
