### ISSUE TITLE
feature: js v8 engine

### ISSUE THREAD

**Issue by sundy-li** [risingwavelabs/arrow-udf#58]
perhaps v8 is a better choice than quickjs if we want better performance

1. https://bellard.org/quickjs/bench.html
2. https://github.com/denoland/rusty_v8

**Comment by wangrunji0408** [comment]
We already have [the deno backend](https://github.com/risingwavelabs/arrow-udf/tree/main/arrow-udf-js-deno) for js contributed by @bakjos. Is it what you want?
